Exception name 'os' is not defined occurred in main of file script.py...
Arguments parsed successfully...
